/**
 * Audit Export — generates 4-sheet Excel workbook for LHDN 7-year audit vault
 * Sheet 1: Tax Summary | Sheet 2: Relief Breakdown | Sheet 3: Record List | Sheet 4: Audit Checklist
 * Uses SheetJS (xlsx) — open-source licensed
 */

import type { Record, Profile, Settings } from '@/store'
import { BE_CODES, getRulesForYA } from '@/lib/lhdn-rules'

interface ReliefTotals {
  [categoryId: string]: number
}

interface TaxSummary {
  grossIncome: number
  epf: number
  socso: number
  pcb: number
  reliefTotal: number
  chargeableIncome: number
  estimatedTax: number
  taxAfterRebate: number
  balance: number
}

const COL_WIDTHS_SUMMARY = [{ wch: 38 }, { wch: 18 }]
const COL_WIDTHS_RELIEF  = [{ wch: 5 }, { wch: 8 }, { wch: 36 }, { wch: 14 }, { wch: 10 }, { wch: 12 }, { wch: 10 }, { wch: 20 }]
const COL_WIDTHS_RECORDS = [{ wch: 5 }, { wch: 12 }, { wch: 24 }, { wch: 28 }, { wch: 22 }, { wch: 18 }, { wch: 10 }, { wch: 12 }, { wch: 8 }, { wch: 34 }, { wch: 18 }]
const COL_WIDTHS_CHECKLIST = [{ wch: 6 }, { wch: 26 }, { wch: 55 }, { wch: 16 }]

function rm(n: number | undefined | null) {
  if (n === undefined || n === null) return 'RM 0.00'
  return `RM ${n.toLocaleString('en-MY', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function pct(val: number, cap: number) {
  if (!cap) return '—'
  return `${Math.min(100, Math.round((val / cap) * 100))}%`
}

function retainUntilDate(taxYear: number): string {
  return `${taxYear + 7}-04-30`
}

export async function generateAuditExcel(
  records: Record[],
  profile: Profile,
  settings: Settings,
  reliefTotals: ReliefTotals,
  tax: TaxSummary,
  taxYear: number
): Promise<Blob> {
  const { utils, write } = await import('xlsx')
  const wb = utils.book_new()
  const ya = `YA ${taxYear}`
  const yearRules = getRulesForYA(taxYear)
  const yearRecords = records.filter((r) => r.date.startsWith(String(taxYear)))

  // ── Sheet 1: Tax Summary ─────────────────────────────────────────────────
  const summaryRows = [
    ['ReliefTrack MY — Audit Summary', ya],
    [],
    ['Taxpayer Name', profile.name || '—'],
    ['Filing Type', 'BE (Resident Individual, Employment Income)'],
    ['Year of Assessment', taxYear],
    ['Filing Deadline', `30 April ${taxYear + 1}`],
    ['Retain Until', retainUntilDate(taxYear)],
    [],
    ['INCOME & DEDUCTIONS', ''],
    ['Gross Employment Income', rm(tax.grossIncome)],
    ['EPF (Employee Contribution)', rm(tax.epf)],
    ['SOCSO / EIS', rm(tax.socso)],
    ['Total Relief Claimed', rm(tax.reliefTotal)],
    ['Chargeable Income', rm(tax.chargeableIncome)],
    [],
    ['TAX COMPUTATION', ''],
    ['Estimated Annual Tax', rm(tax.estimatedTax)],
    ['Less: Rebate (RM 400 if CI ≤ RM 35,000)', '—'],
    ['Tax After Rebate', rm(tax.taxAfterRebate)],
    ['PCB Deducted (from EA Form)', rm(tax.pcb)],
    ['Estimated Balance Payable / (Refund)', rm(tax.balance)],
    [],
    ['NOTES', ''],
    ['Generated by', 'ReliefTrack MY'],
    ['Generated on', new Date().toLocaleDateString('en-MY')],
    ['Disclaimer', 'For reference only. Verify against MyTax (mytax.hasil.gov.my) before submission.'],
  ]
  const wsSummary = utils.aoa_to_sheet(summaryRows)
  wsSummary['!cols'] = COL_WIDTHS_SUMMARY
  utils.book_append_sheet(wb, wsSummary, 'Tax Summary')

  // ── Sheet 2: Relief Breakdown ────────────────────────────────────────────
  const reliefHeader = ['#', 'BE Code', 'Category', 'Claimed (RM)', 'Cap (RM)', 'Utilised %', 'Records', 'Evidence Complete?']
  const reliefRows = [reliefHeader]
  let rowNum = 0
  let claimedTotal = 0
  let capTotal = 0
  let recordsTotal = 0

  for (const rule of yearRules) {
    const claimed = reliefTotals[rule.categoryId] ?? 0
    const cap = rule.totalCap
    const recs = yearRecords.filter((r) => r.category === rule.categoryId).length
    const withReceipt = yearRecords.filter((r) => r.category === rule.categoryId && r.receiptUrl).length
    const evidenceStatus = rule.autoApply
      ? 'Auto (no receipt needed)'
      : recs === 0
        ? '—'
        : withReceipt === recs
          ? '✓ All receipts attached'
          : `⚠ ${recs - withReceipt} missing`

    rowNum++
    reliefRows.push([
      rowNum,
      rule.beCode,
      rule.label,
      claimed > 0 ? claimed.toFixed(2) : '0.00',
      cap > 0 ? cap.toFixed(2) : 'Unlimited',
      cap > 0 ? pct(claimed, cap) : '—',
      recs > 0 ? recs : rule.autoApply ? 'Auto' : 0,
      evidenceStatus,
    ])
    claimedTotal += claimed
    if (cap > 0) capTotal += cap
    recordsTotal += recs
  }

  reliefRows.push([])
  reliefRows.push(['', '', 'TOTAL', claimedTotal.toFixed(2), capTotal.toFixed(2), pct(claimedTotal, capTotal), recordsTotal, ''])

  const wsRelief = utils.aoa_to_sheet(reliefRows)
  wsRelief['!cols'] = COL_WIDTHS_RELIEF
  utils.book_append_sheet(wb, wsRelief, 'Relief Breakdown')

  // ── Sheet 3: Full Record List ────────────────────────────────────────────
  const recordHeader = ['#', 'Date', 'Merchant', 'Description', 'Category', 'Sub-category', 'Recipient', 'Amount (RM)', 'LHDN Code', 'Receipt File', 'Audit Status']
  const recordRows = [recordHeader]

  yearRecords
    .sort((a, b) => a.date.localeCompare(b.date))
    .forEach((r, i) => {
      const beCode = BE_CODES[r.category] ?? '—'
      const receiptFile = r.receiptFileName || (r.receiptUrl ? '(attached)' : '—')
      const auditStatus = r.receiptUrl
        ? '✓ Receipt attached'
        : r.category === 'individual'
          ? '✓ Automatic relief'
          : '⚠ No receipt'

      recordRows.push([
        i + 1,
        r.date,
        r.merchant,
        r.description || '—',
        r.category.replace(/_/g, ' '),
        r.lhdNCategory || '—',
        r.recipient || 'self',
        r.amount.toFixed(2),
        beCode,
        receiptFile,
        auditStatus,
      ])
    })

  const wsRecords = utils.aoa_to_sheet(recordRows)
  wsRecords['!cols'] = COL_WIDTHS_RECORDS
  utils.book_append_sheet(wb, wsRecords, 'Record List')

  // ── Sheet 4: Audit Checklist ─────────────────────────────────────────────
  const checkRows: (string | number)[][] = [
    ['LHDN Audit Readiness Checklist', ya, '', ''],
    [],
    ['#', 'Requirement', 'Action / Notes', 'Status'],
  ]

  let checkNum = 0
  for (const rule of yearRules) {
    const claimed = reliefTotals[rule.categoryId] ?? 0
    if (claimed === 0 && !rule.autoApply) continue

    checkNum++
    const recs = yearRecords.filter((r) => r.category === rule.categoryId)
    const withReceipt = recs.filter((r) => r.receiptUrl)

    let action = ''
    let status = ''

    if (rule.autoApply) {
      action = 'No receipt needed — automatic relief'
      status = '✓ Ready'
    } else if (recs.length === 0) {
      action = `Claimed RM ${claimed.toFixed(2)} but no records found — add receipts`
      status = '⚠ Action needed'
    } else if (withReceipt.length < recs.length) {
      action = `${withReceipt.length}/${recs.length} receipts attached — attach missing: ${rule.evidence.description}`
      status = '⚠ Incomplete'
    } else {
      action = rule.evidence.requiresCertification
        ? `All receipts attached. Note: specialist certification may be required for serious disease claims.`
        : `All ${recs.length} receipts attached.`
      status = '✓ Ready'
    }

    checkRows.push([checkNum, `${rule.beCode}: ${rule.label}`, action, status])
  }

  checkRows.push([])
  checkRows.push(['', 'Retain Until', retainUntilDate(taxYear), '7 years from filing date per LHDN'])
  checkRows.push(['', 'For questions', 'Contact LHDN: +603-8913 3800 or hasil.gov.my', ''])

  const wsChecklist = utils.aoa_to_sheet(checkRows)
  wsChecklist['!cols'] = COL_WIDTHS_CHECKLIST
  utils.book_append_sheet(wb, wsChecklist, 'Audit Checklist')

  // Write workbook to buffer
  const buf = write(wb, { type: 'array', bookType: 'xlsx' })
  return new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
}

export function downloadAuditExcel(blob: Blob, taxYear: number) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `_Summary_YA${taxYear}.xlsx`
  a.click()
  URL.revokeObjectURL(url)
}
